const instrumentList = [
    "Accordian",
    "Bagpipes",
    "Banjo",
    "Bongos",
    "Cello",
    "Clarinet",
    "Bass Clarinet",
    "Contrabass Clarinet",
    "Cornet",
    "Double Bass",
    "Drum Kit",
    "English Horn",
    "Euphonium",
    "Flute",
    "Bass Flute",
    "French Horn",
    "Glockenspiel",
    "Acoustic Guitar",
    "Bass Guitar",
    "Electric Guitar",
    "Harmonica",
    "Harp",
    "Harpsichord",
    "Hammered Dulcimer",
    "Kalimba",
    "Lute",
    "Lyre",
    "Mandolin",
    "Marimba",
    "Melodica",
    "Oboe",
    "Ocarina",
    "Organ",
    "Otamatone",
    "Pan Pipes",
    "Pennywhistle",
    "Percussion (General)",
    "Piano",
    "Piccolo",
    "Recorder",
    "Alto Saxophone",
    "Tenor Saxophone",
    "Baritone Saxophone",
    "Soprano Saxophone",
    "Stylophone",
    "Timpani", 
    "Trombone",
    "Bass Trombone",
    "Trumpet",
    "Flugelhorn",
    "Piccolo Trumpet",
    "Theremin",
    "Tuba",
    "Ukulele",
    "Vibraphone",
    "Viola",
    "Violin",
    "Xylophone",
    "Vocals"
]
const instrumentListLength = instrumentList.length;

module.exports = {instrumentList, instrumentListLength};